# Analiza podataka dobijenih simulacijom u SUMO-GUI okruzenju
## Import svih potrebnih biblioteka za analizu

In [1]:
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine

import movingpandas as mpd
from shapely.geometry import Point
import folium
import numpy as np

C:\D\GIS\GIS-GIT\GIS-GIT\Project 3\sumo_postgis\venv\Lib\site-packages\movingpandas\__init__.py:41: UserWarning: Missing optional dependencies. To use the trajectory smoother classes please install Stone Soup (see https://stonesoup.readthedocs.io/en/latest/#installation).
  warnings.warn(e.msg, UserWarning)

## Uspostavljanje konekcije sa PostGIS bazom podataka

In [2]:
engine = create_engine("postgresql://postgres:Petsre971$$$@localhost:5432/sumo_db")

## Uzimanje podataka ( vozila ) iz PostGIS baze podataka

In [3]:
fcd = gpd.read_postgis(
    """
    SELECT *
    FROM fcd_tracks
    """,
    engine,
    geom_col="geom"
)

#ovo sam napisao jer sam greskom oznacio geom podatke u POSTGIS pri importovanju podataka da su EPSG:3857
#umesto EPSG:4326 pa ispravljam gresku naknadno, plus konvertujem u EPSG:3857 jer je bolje za analizu u ovom slucaju
fcd = fcd.set_crs(4326, allow_override=True).to_crs(3857)

#ispravljaju se i x/y kolone tako da budu u ispravnom koodrinatnom sistemu
fcd["x"] = fcd.geometry.x
fcd["y"] = fcd.geometry.y

print("FCD shape:", fcd.shape)
print("\nKolone:", fcd.columns)
print("\nPrvih 5 redova:")
display(fcd.head())

FCD shape: (1756660, 11)

Kolone: Index(['vehicle_id', 'time', 'x', 'y', 'angle', 'type', 'speed', 'pos', 'lane',
       'slope', 'geom'],
      dtype='str')

Prvih 5 redova:

,vehicle_id,time,x,y,angle,type,speed,pos,lane,slope,geom
0,bus0,0.0,478648.986165,6.816522e+06,335.41,bus_bus,8.33,12.10,7493814_0,0.0,POINT (478648.986 6816521.529)
1,motorcycle0,0.0,479878.509940,6.817127e+06,153.28,motorcycle_motorcycle,13.89,2.30,-200026251#2_0,0.0,POINT (479878.51 6817127.054)
2,truck0,0.0,479328.146378,6.817549e+06,130.27,truck_truck,8.46,7.20,-7475252_0,0.0,POINT (479328.146 6817549.246)
3,veh0,0.0,479826.746377,6.816928e+06,330.37,veh_passenger,13.89,5.10,7477284#0_0,0.0,POINT (479826.746 6816927.925)
4,bus0,1.0,478642.529634,6.816533e+06,330.31,bus_bus,8.22,20.32,7493814_0,0.0,POINT (478642.53 6816533.306)

## konverzija formata vremena iz sekundi u datetime, jer movingpandas radi sa datetime formatom

In [4]:
import datetime

base_time = pd.Timestamp("2026-01-01")

fcd["t"] = base_time + pd.to_timedelta(fcd["time"], unit="s")

#sada svi vremenski podaci su konvertovani iz sekunda u 2026-01-01 + offset (tj broj sekunda).

print("Primeri vremenskih kolona:")
display(fcd[["time", "t"]].head())

print("Vremenski opseg:")
print(fcd["t"].min(), "→", fcd["t"].max())

Primeri vremenskih kolona:

   time                   t
0   0.0 2026-01-01 00:00:00
1   0.0 2026-01-01 00:00:00
2   0.0 2026-01-01 00:00:00
3   0.0 2026-01-01 00:00:00
4   1.0 2026-01-01 00:00:01

Vremenski opseg:
2026-01-01 00:00:00 → 2026-01-01 00:59:59

# Analiza 6 : Zastoji – ulice sa najmanjom prosečnom brzinom vozila

In [5]:
import branca.colormap as cm
from shapely.geometry import LineString

In [6]:
# postavljanje vremenskog intervala za koji se vrši analiza
start_time = pd.Timestamp("2026-01-01 00:00:00")
end_time = pd.Timestamp("2026-01-01 01:00:00")

print("ukupna kolicina podataka:", len(fcd))
print("vremenski opseg:", fcd["t"].min(), "→", fcd["t"].max())
print()

ukupna kolicina podataka: 1756660
vremenski opseg: 2026-01-01 00:00:00 → 2026-01-01 00:59:59

In [7]:
#filtriranje fcd podataka tako da samo ostanu podaci koji su u traženom vremenskom periodu
period = fcd[
    (fcd["t"] >= start_time) &
    (fcd["t"] <= end_time)
].copy()

print("ukupna količina filtriranih podataka:", len(period))
print("ukupan broj vozila:", period["vehicle_id"].nunique())
print()

ukupna količina filtriranih podataka: 1756660
ukupan broj vozila: 2375

In [8]:
# pravljenje liste statistike tako što se filtrirani podaci iz fcd grupišu po lane-u, uzimaju se brzine iz zabeležene u tom lane-u
# zatim se računa prosek i dobija se novi DataFrame gde imamo dve kolone lane i avg_speed
speed_stats = (
    period.groupby("lane")["speed"]
    .mean()
    .reset_index(name="avg_speed")
)

print("top 10 najbržih lane-ova:")
print(speed_stats.sort_values("avg_speed", ascending=False).head(10))
print()

print("top 10 najsporijih lane-ova:")
print(speed_stats.sort_values("avg_speed").head(10))
print()

top 10 najbržih lane-ova:
                                    lane  avg_speed
149                       1505707610#0_1  16.600000
147                         1505510651_1  14.718276
437                     :13773430500_0_1  14.500000
214                          444314259_1  14.448333
879                        :45222550_1_1  14.280000
1120   :cluster_413394652_8551649496_6_0  14.216429
424                      :1165729396_0_0  14.120000
1012  :cluster_1165729110_1165729566_1_1  14.087647
365                          837553903_0  14.035000
100                        100876531#0_1  13.985161

top 10 najsporijih lane-ova:
                                                   lane  avg_speed
220                                         461164969_1   0.000000
398                                     :1165729136_3_0   0.015231
871                                       :45221351_1_0   0.023669
1131                     :cluster_45211629_45212465_5_0   0.024206
327                                         7477236#1_1   0.036931
162                                        1521892286_0   0.043364
52                                           -7477131_0   0.049033
835                                      :45219439_10_0   0.052750
803                                       :45216491_5_0   0.055769
951   :cluster_1164135846_1164135877_1164135881_1164...   0.061252

In [9]:
# kao i u prethodnom primeru formiraju se linestring-ovi tako što uzmemo filtrirane fcd podatke, sortiramo po vremenu 
#  grupišemo po lane-u, konstruišemo listu parova koordinata za lane, konstruišemo linestring i dodajemo listi
# i na kraju od liste linestring-ova konstruišemo GeoDataFrame

# podaci se sortiraju po vremenu kako bi tačke u LineString-u pratile redosled kretanja
period_sorted = period.sort_values("t")

lane_lines = []

for lane, group in period_sorted.groupby("lane"):

    coords = list(zip(group["x"], group["y"]))

    # radi bržeg prikaza i manje memorijske potrošnje zadržava se svaka treća tačka
    coords = coords[::3]

    # uklanjaju se duplikati koordinata kako bi se izbegle nepotrebne tačke u geometriji
    coords = list(dict.fromkeys(coords))
    
    if len(coords) < 2:
        continue

    lane_lines.append({
        "lane": lane,
        "geometry": LineString(coords)
    })

lane_gdf = gpd.GeoDataFrame(
    lane_lines,
    geometry="geometry",
    crs="EPSG:3857"
)

In [10]:
# geometrije lane-ova spajaju se sa tabelom prosečnih brzina koristeći kolonu "lane"
result = lane_gdf.merge(speed_stats, on="lane")

# zadržava se 60 lane-ova sa najmanjom prosečnom brzinom radi preglednije vizuelizacije
result = result.sort_values("avg_speed", ascending=True).head(60)

print("Broj lane-ova nakon filtriranja:", len(result))

Broj lane-ova nakon filtriranja: 60

In [11]:
print("geometrije:")
print(result.geometry.geom_type.value_counts())
print()

print("Statistika o prosečnim brzinama:")
print(result["avg_speed"].describe())
print()

# sanity check u slučaju da postoje neke čudne brzine
print("Min prosečna brzina:", result["avg_speed"].min())
print("Max prosečna brzina:", result["avg_speed"].max())
print()

geometrije:
LineString    60
Name: count, dtype: int64

Statistika o prosečnim brzinama:
count    60.000000
mean      0.154356
std       0.065709
min       0.015231
25%       0.101929
50%       0.168667
75%       0.205592
max       0.244729
Name: avg_speed, dtype: float64

Min prosečna brzina: 0.015230557467309015
Max prosečna brzina: 0.2447286821705426

In [12]:
print("ukupan broj lane-ova:", len(result))

print("Statistika broja tačaka po LineString-u:")
print(result.geometry.apply(lambda g: len(g.coords)).describe())

print("maksimalan broj tačaka u bilo kojem linestring-u:")
print(result.geometry.apply(lambda g: len(g.coords)).max())

ukupan broj lane-ova: 60
Statistika broja tačaka po LineString-u:
count     60.000000
mean      69.650000
std      116.753082
min        2.000000
25%        4.000000
50%        9.000000
75%       79.500000
max      451.000000
Name: geometry, dtype: float64
maksimalan broj tačaka u bilo kojem linestring-u:
451

In [13]:
# na kraju na potpuno istovetan način kao i sa prošlom analizom kreiramo folium mapu.

# geometrije se uprošćavaju kako bi renderovanje mape bilo brže
result["geometry"] = result["geometry"].simplify(2)

# geometrije se reprojektuju u EPSG:4326 jer Folium koristi geografske koordinate
result = result.to_crs(4326)

center_geom = result.geometry.union_all().centroid
center = [center_geom.y, center_geom.x]

m = folium.Map(
    location=center,
    zoom_start=13,
    tiles="CartoDB positron"
)

# definiše se kolor mapa kojom se prosečne brzine vizuelno predstavljaju različitim bojama
colormap = cm.LinearColormap(
    colors=[
        "#FF0000",  # crvena (manja brzina)
        "#FFA500",  # narandžasta
        "#FFD580",  # svetlonarandžasta
        "#00FF00"   # zelena (veća brzina)
    ],
    vmin=result["avg_speed"].min(),
    vmax=result["avg_speed"].max()
)


for row in result.itertuples():

    coords = [(y, x) for x, y in row.geometry.coords]

    folium.PolyLine(
        locations=coords,
        color=colormap(row.avg_speed),
        weight=4,
        opacity=0.85,
        tooltip=f"{row.lane} | {row.avg_speed:.2f} m/s"
    ).add_to(m)

colormap.caption = "Average Speed (m/s)"
colormap.add_to(m)

print("lane-ovi:", len(result))
print("prosečna brzina (min/max):", result["avg_speed"].min(), result["avg_speed"].max())

m

lane-ovi: 60
prosečna brzina (min/max): 0.015230557467309015 0.2447286821705426